### ISSUE TITLE
race condition in async archive-push?

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#91] opened 2015-05-29 17:14 UTC
I'm seeing errors on a regular basis on a high-throughput database - seems to happen when two WAL segments are pushed in short succession. The segments are eventually pushed to the remote backrest server, so there's no data loss.

pg_backrest.conf on database side:

```
[global:backup]
backup-host=prd-ba-01
backup-user=backrest

[global:general]
repo-path=/data/postgresql/wal-spool
repo-remote-path=/data/postgresql/backups

[global:log]
log-level-console=info

[global:archive]
archive-async=y
archive-max-mb=4096

[prd-psql3-01]
db-path=/data/postgresql/9.3/main
```

pg_backrest log:

```
-------------------PROCESS START-------------------
2015-05-29 16:02:10.041 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 16:02:11.980 T00   INFO: archive to be copied to backup total 2, size 32MB
2015-05-29 16:02:11.980 T00  ERROR: [116]: unable to open /data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED3000000AD-753252ed2a19f94446a6b581ab3622b485e6a71c
 at /opt/backrest/bin/../lib/BackRest/Archive.pm line 173.
                                        BackRest::Archive::walInfo('BackRest::Archive=HASH(0x22fa9a8)', '/data/postgresql/wal-spool/archive/prd-psql3-01...') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 672
                                        BackRest::Archive::xfer('BackRest::Archive=HASH(0x22fa9a8)', '/data/postgresql/wal-spool/archive/prd-psql3-01...', '/data/postgresql/wal-spool/lock/prd-psql3-01...') called at /opt/backrest
/bin/../lib/BackRest/Archive.pm line 409
                                        BackRest::Archive::pushProcess('BackRest::Archive=HASH(0x22fa9a8)') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 66
                                        BackRest::Archive::process('BackRest::Archive=HASH(0x22fa9a8)') called at /opt/backrest/bin/pg_backrest.pl line 141
                                        eval {...} called at /opt/backrest/bin/pg_backrest.pl line 125

                                   2015-05-29 16:02:12.063 T00   INFO: archive to be copied to backup total 1, size 16MB

[..]

-------------------PROCESS START-------------------
2015-05-29 17:00:55.047 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 17:00:57.029 T00   INFO: archive to be copied to backup total 2, size 32MB
2015-05-29 17:00:57.029 T00  ERROR: [116]: unable to open /data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED400000035-6693e84ab158dd65387d352efd58e145327f2c6f
 at /opt/backrest/bin/../lib/BackRest/Archive.pm line 173.
                                        BackRest::Archive::walInfo('BackRest::Archive=HASH(0x7ca678)', '/data/postgresql/wal-spool/archive/prd-psql3-01...') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 672
                                        BackRest::Archive::xfer('BackRest::Archive=HASH(0x7ca678)', '/data/postgresql/wal-spool/archive/prd-psql3-01...', '/data/postgresql/wal-spool/lock/prd-psql3-01...') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 409
                                        BackRest::Archive::pushProcess('BackRest::Archive=HASH(0x7ca678)') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 66
                                        BackRest::Archive::process('BackRest::Archive=HASH(0x7ca678)') called at /opt/backrest/bin/pg_backrest.pl line 141
                                        eval {...} called at /opt/backrest/bin/pg_backrest.pl line 125

                                   2015-05-29 17:00:57.288 T00   INFO: archive to be copied to backup total 1, size 16MB
```

Relevant output from postgres log for the second occurence:

```
2015-05-29 17:00:54.580 T00   INFO: pushing WAL segment pg_xlog/0000000100001ED400000035 asynchronously
2015-05-29 17:00:54.731 T00   INFO: starting async archive-push
2015-05-29 17:00:56.566 T00   INFO: pushing WAL segment pg_xlog/0000000100001ED400000036 asynchronously
2015-05-29 17:00:56.715 T00   INFO: starting async archive-push
2015-05-29 17:00:55.047 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 17:00:57.029 T00   INFO: archive to be copied to backup total 2, size 32MB
2015-05-29 17:00:57.029 T00  ERROR: [116]: unable to open /data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED400000035-6693e84ab158dd65387d352efd58e145327f2c6f
2015-05-29 17:00:57.288 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 17:01:01.086 T00   INFO: pushing WAL segment pg_xlog/0000000100001ED400000037 asynchronously
2015-05-29 17:01:01.244 T00   INFO: starting async archive-push
2015-05-29 17:01:01.559 T00   INFO: archive to be copied to backup total 1, size 16MB
```

**Comment by dwsteele** [comment] 2015-05-29 17:21
Hmmm - it looks like more than one async process is getting spawned.

**Comment by dwsteele** [comment] 2015-05-29 17:21
BTW - which commit are you running?

**Comment by terrorobe** [comment] 2015-05-29 17:22
From a different server, identical configuration. Different error, maybe related?

Currently running 6d2f2d3f91227dffe635ab14de3db3d83c09e0c6

```
-------------------PROCESS START-------------------
2015-05-29 16:30:04.605 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 16:30:05.236 T00   INFO: archive to be copied to backup total 3, size 48MB
2015-05-29 16:30:04.874 T00   INFO: archive to be copied to backup total 2, size 32MB
2015-05-29 16:30:06.948 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 16:30:07.755 T00 ASSERT: no lock is currently held
 at /opt/backrest/bin/../lib/BackRest/Lock.pm line 107.
                                        BackRest::Lock::lockRelease() called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 421
                                        BackRest::Archive::pushProcess('BackRest::Archive=HASH(0x1d43768)') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 66
                                        BackRest::Archive::process('BackRest::Archive=HASH(0x1d43768)') called at /opt/backrest/bin/pg_backrest.pl line 141
                                        eval {...} called at /opt/backrest/bin/pg_backrest.pl line 125

                                   2015-05-29 16:30:07.756 T00  ERROR: process terminated on signal or exception, 0 threads stopped
 at /opt/backrest/bin/pg_backrest.pl line 115.
                                        main::safe_exit() called at /opt/backrest/bin/pg_backrest.pl line 302
```

**Comment by terrorobe** [comment] 2015-05-29 17:27
If it helps with debugging I can keep it running in trace mode on one node?

**Comment by dwsteele** [comment] 2015-05-29 17:29
Just debug would be fine.  Trace is mostly protocol layer logging and I don't think that's the issue here.

**Comment by dwsteele** [comment] 2015-05-29 17:38
OK - I see it.  I'll have a fix soon.

**Comment by terrorobe** [comment] 2015-05-29 19:13
fwiw - here's a debug snippet:

```
-------------------PROCESS START-------------------
2015-05-29 18:01:13.477 T00  DEBUG:     File->manifest: db:absolute:/data/postgresql/wal-spool/archive/prd-psql3-01/out
2015-05-29 18:01:12.095 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 18:01:12.095 T00  DEBUG:     archive 0000000100001ED4000000BA-e39094dfc6246cc32eab0db38f0dc2e077252cd8, is WAL 1, source_compressed = 0, destination_compress 1,
 default_compress = 1
2015-05-29 18:01:12.096 T00  DEBUG:     Archive->pushCheck: backup:archive:0000000100001ED4000000BA
2015-05-29 18:01:12.099 T00  DEBUG:     File->copy:  local db:absolute:/data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED4000000BA-e39094d
fc6246cc32eab0db38f0dc2e077252cd8 to remote backup:archive:/data/postgresql/backups/archive/prd-psql3-01/0000000100001ED4/0000000100001ED4000000BA-e39094df
c6246cc32eab0db38f0dc2e077252cd8.gz, source_compressed = false, destination_compress = true, ignore_missing_source = false, destination_path_create = true, modification_ti
me = [undef], mode = [undef], user = [undef], group = [undef]
2015-05-29 18:01:13.781 T00  DEBUG:     1 WAL segments were transferred, calling Archive->xfer() again
2015-05-29 18:01:13.782 T00  DEBUG:     File->manifest: db:absolute:/data/postgresql/wal-spool/archive/prd-psql3-01/out
2015-05-29 18:01:13.797 T00   INFO: archive to be copied to backup total 2, size 32MB
2015-05-29 18:01:13.797 T00  DEBUG:     archive 0000000100001ED4000000BA-e39094dfc6246cc32eab0db38f0dc2e077252cd8, is WAL 1, source_compressed = 0, destination_compress 1,
 default_compress = 1
2015-05-29 18:01:13.798 T00  ERROR: [116]: unable to open /data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED4000000BA-e39094dfc6246cc32eab
0db38f0dc2e077252cd8
 at /opt/backrest/bin/../lib/BackRest/Archive.pm line 173.
                                        BackRest::Archive::walInfo('BackRest::Archive=HASH(0xbd4978)', '/data/postgresql/wal-spool/archive/prd-psql3-01...')
called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 672
                                        BackRest::Archive::xfer('BackRest::Archive=HASH(0xbd4978)', '/data/postgresql/wal-spool/archive/prd-psql3-01...', '/d
ata/postgresql/wal-spool/lock/prd-psql3-01-...') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 409
                                        BackRest::Archive::pushProcess('BackRest::Archive=HASH(0xbd4978)') called at /opt/backrest/bin/../lib/BackRest/Archive.pm line 66
                                        BackRest::Archive::process('BackRest::Archive=HASH(0xbd4978)') called at /opt/backrest/bin/pg_backrest.pl line 141
                                        eval {...} called at /opt/backrest/bin/pg_backrest.pl line 125

                                   2015-05-29 18:01:13.808 T00  DEBUG:     safe exit called, terminating threads
2015-05-29 18:01:14.092 T00   INFO: archive to be copied to backup total 1, size 16MB
2015-05-29 18:01:14.092 T00  DEBUG:     archive 0000000100001ED4000000BB-d32f25ceb8382a1147fddadfbbb6a111bbf4421a, is WAL 1, source_compressed = 0, destination_compress 1,
 default_compress = 1
2015-05-29 18:01:14.093 T00  DEBUG:     Archive->pushCheck: backup:archive:0000000100001ED4000000BB
2015-05-29 18:01:14.096 T00  DEBUG:     File->copy:  local db:absolute:/data/postgresql/wal-spool/archive/prd-psql3-01/out/0000000100001ED4000000BB-d32f25c
eb8382a1147fddadfbbb6a111bbf4421a to remote backup:archive:/data/postgresql/backups/archive/prd-psql3-01/0000000100001ED4/0000000100001ED4000000BB-d32f25ce
b8382a1147fddadfbbb6a111bbf4421a.gz, source_compressed = false, destination_compress = true, ignore_missing_source = false, destination_path_create = true, modification_ti
me = [undef], mode = [undef], user = [undef], group = [undef]
2015-05-29 18:01:15.512 T00  DEBUG:     1 WAL segments were transferred, calling Archive->xfer() again
2015-05-29 18:01:15.513 T00  DEBUG:     File->manifest: db:absolute:/data/postgresql/wal-spool/archive/prd-psql3-01/out
2015-05-29 18:01:15.513 T00  DEBUG:     no archive logs to be copied to backup
2015-05-29 18:01:15.513 T00  DEBUG:     no more WAL segments to transfer - exiting
2015-05-29 18:01:15.514 T00  DEBUG:     safe exit called, terminating threads
```

**Comment by dwsteele** [comment] 2015-05-29 19:18
This log makes it clear that there are two async process running at the same time.  I'm doing regression on the fix right now.

**Comment by dwsteele** [comment] 2015-05-29 20:32
Fixed in e7d2d70.

**Closed by dwsteele** 2015-05-29 20:32 UTC
Labels: bug (code), High Priority

**Comment by terrorobe** [comment] 2015-06-01 10:55
Deployed in production, works fine!

**Comment by dwsteele** [comment] 2015-06-01 15:01
Excellent - thanks!  0.70 has now been released.
